title: Ben Katz Data Science Portfolio 
logo: "https://github.com/bkatz21/bkatz21.github.io/blob/master/images/Screen%20Shot%202022-04-13%20at%2011.12.54%20AM.png" # your photo (or logo) here
description: Here is where you can find all of the data science projects I have or am currently working on. > 

  <a href="www.linkedin.com/in/benkatz21">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
